version: "3.9"

services:

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: memora_backend
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: memora_frontend
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always